#!/usr/bin/python
#coding=utf-8
import os,sys,getopt
import WeatherFunc

def usage():
	print '''使用参数：
        pyweather         (没有参数，根据设定的默认值查询) 
        pyweather  -a     (-auto 联网后根据IP所在地，自动获取本地天气) 
        pyweather  -s   [cityname]  (-set设定默认查询天气的城市) 
        pyweather  -c   [cityname]  (-city 查询指定城市的天气) 
        pyweather  -A   (所有城市的天气) 
 '''	
argc=len(sys.argv)

if argc==1:
	print 'weather_info_default'
	st=WeatherFunc.weatherinfo_by_default_name()
	WeatherFunc.print_weather_info(st)
elif argc==2:
	if sys.argv[1]=='-a':
		st=WeatherFunc.auto_get_weather_info()
		WeatherFunc.print_weather_info(st)
	elif sys.argv[1]=='-A':
		print '更新所有天气缓存'
		WeatherFunc.weatherinfo_create_allcity_cache()
	else:
		usage()

elif argc==3:
	if sys.argv[1]=='-s':
		if True==WeatherFunc.set_default_cityname(sys.argv[2]):
			print 'set default cityname[%s] success'%(sys.argv[2])
		else:
			print 'set default cityname[%s] fail'%(sys.argv[2])
		
	elif sys.argv[1]=='-c':
		st=WeatherFunc.weatherinfo_byname(sys.argv[2])
		WeatherFunc.print_weather_info(st)
	else:
		usage()
else:
	usage()
